### ISSUE TITLE
Failure on removing "$"?

### ISSUE THREAD

**Issue by olegbl** [mame/radiation-hardened-quine#2]
Removing the very first $ (after `eval='eval`) in the program seems to cause it to fail to parse.

diff

```
~/t/radiation-hardened-quine$ diff rquine.rb rquine.2.rb
1c1
< eval='eval$q=%q(puts %q(10210/#{1 1 if 1==21}}/.i rescue##/

---
> eval='evalq=%q(puts %q(10210/#{1 1 if 1==21}}/.i rescue##/
```

error

```
~/t/radiation-hardened-quine$ ruby rquine.2.rb > output && diff rquine.rb output
rquine.2.rb:15: warning: regexp has `}' without escape
```

**Comment by mame** [comment]
What version of Ruby are you running?  I confirmed 1.9.3p194 and 2.1.0p0.
Anyway, I believe it works actually.  The message is just a warning.  Try:

```
ruby rquine.2.rb > output && diff rquine.rb output && echo success
```

**Comment by olegbl** [comment]
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
Yes, you're right. It went through fine, just printed the warning.
My bad, good stuff =)
